---
# file: roles/common/tasks/main.yml

- name: disable NetworkManager
  service: enabled=no name=NetworkManager state=stopped
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'

- name: enable network
  service: enabled=yes name=network state=started

- name: disable firewalld
  service: enabled=no name=firewalld state=stopped
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'

- name: enable iptables
  service: enabled=yes name=iptables state=started

- name: install libselinux-python
  yum: pkg=libselinux-python state=present

- name: "Build hosts file"
#  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
#  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all'] 

- name: install misc items
  yum: pkg={{ item }} state=installed
  with_items:
   - vim
   - wget
   - tcpdump
   - curl

- name: install ntp      
  yum: name=ntp state=present

- name: enable ntp
  service: enabled=yes name=ntpd state=started

- name: install database on controller
  yum: pkg={{ item }} state=installed
  with_items:
   - mariadb
   - mariadb-server
   - MySQL-python
  when: ansible_hostname == "controller"

- name: install OpenStack repos and packages
  yum: pkg={{item}} state=installed
  with_items:
   - yum-plugin-priorities
   - http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
   - http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm
   - openstack-utils
   - openstack-selinux

- name: create /etc/my.cnf.d/mariadb_openstack.cnf
  shell: "{{ item }}"
  with_items:
   - crudini --set /etc/my.cnf.d/mariadb_openstack.cnf mysqld default-storage-engine innodb
   - crudini --set /etc/my.cnf.d/mariadb_openstack.cnf mysqld innodb_file_per_table true
   - crudini --set /etc/my.cnf.d/mariadb_openstack.cnf mysqld collation-server utf8_general_ci
   - crudini --set /etc/my.cnf.d/mariadb_openstack.cnf mysqld init-connect 'SET NAMES utf8'
   - crudini --set /etc/my.cnf.d/mariadb_openstack.cnf mysqld character-set-server utf8
  when: ansible_hostname == "controller"
  notify:
     - restart mariadb

- name: enable database
  service: enabled=yes name=mariadb state=started
  when: ansible_hostname == "controller"

- name: mysql db install
  command: mysql_install_db
  when: ansible_hostname == "controller"

- name: database stuffs
  command: /usr/bin/mysqladmin -u root password '{{ MYSQL_ADMIN_PASS }}'
  when: ansible_hostname == "controller"

- name: database root user password set
#  command: /usr/bin/mysqladmin -u root -h {{ CONTROLLER }} password '{{ MYSQL_ADMIN_PASS }}'
  command: /usr/bin/mysqladmin -u root -h localhost password '{{ MYSQL_ADMIN_PASS }}'
  when: ansible_hostname == "controller"

- name: install database helper libraries on nodes
  yum: pkg=MySQL-python state=present
  when: ansible_hostname == "compute*"

- name: upgrade all packages
  yum: name=* state=latest
  register: updated

- name: install message queue
  yum: name=rabbitmq-server state=present
  when: ansible_hostname == "controller"

- name: rabbitmq add user
  command: rabbitmqctl add_user {{ RABBIT_USER }} {{ RABBIT_PASS }}
  when: ansible_hostname == "controller"

- name: rabbitmq Permit configuration, write, and read access for the openstack user
  command: rabbitmqctl set_permissions {{ RABBIT_USER }} ".*" ".*" ".*"
  when: ansible_hostname == "controller"

- name: enable rabbitmq
  service: enabled=yes name=rabbitmq-server state=started
  when: ansible_hostname == "controller"

- name: install packages for namespaces support
  yum: name=iproute*netns* state=present

- name: install the openstack clients and python-pip
  yum: pkg={{ item }} state=installed
  with_items:
   - python-pip
   - python-novaclient
   - python-neutronclient
   - python-cinderclient
   - python-keystoneclient

- name: reboot
  command: reboot
  when: updated.changed

- name: wait for the server to go down (reboot)
  sudo: false
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=stopped
  when: updated.changed

- name: wait for the server to come up
  sudo: false
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=30 timeout=600
  when: updated.changed

- name: pause 1 minute to allow boot to complete
  pause: seconds=60
  when: updated.changed
